### ISSUE TITLE
AcceptReturn in DataGridTextColumn

### ISSUE THREAD

**Issue by makuepfer** [DavidOndrus/xliff-translator-tool#10]
If you enter a NewLine in the data grid, it will jump to your next record.
Since you are able to import NewLines, it would be nice to be able to enter them as well.

Hint:
![image](https://user-images.githubusercontent.com/28920033/46025331-fcbd2500-c0e8-11e8-9201-9ba4003b7c84.png)

**Comment by DavidOndrus** [comment]
Thanks for your suggestion, I do not want to enable text wrapping so "accepts return" was enough.
Implemented in release 1.5
