### ISSUE TITLE
Fixing scrollbar for DataGrid

### ISSUE THREAD

**Issue by makuepfer** [DavidOndrus/xliff-translator-tool#11]
The scrollbar scrolls through the entire content of your view.
It would be nice if the scrollbar only applies to your DataGrid and the menu stays docked on top of your view.

Suggestion:
Replace the ScrollViewer + StackPanel with a Grid and add two rows (one for the menu and one for the DataGrid). 
![image](https://user-images.githubusercontent.com/28920033/46025741-e9f72000-c0e9-11e8-95c6-c1a3796a71ee.png)

**Comment by DavidOndrus** [comment]
Thanks for your suggestion, I prefer DockPanel instead of the Grid which would be useful for more than 2 items.
Implemented in 1.5
