### ISSUE TITLE
[Question] Skip empty targets in export?

### ISSUE THREAD

**Issue by JaronPiet** [DavidOndrus/xliff-translator-tool#17]
An empty target field will cause an empty target node in the export. That causes also an empty string when the translation file is applied (tested with angular).  The source isn't used as fallback if the target node is empty, but it will be used if the target node isn't existing at all. So maybe it's a good idea to skip empty targets in the export?

**Comment by DavidOndrus** [comment]
Yes, that's a good idea, I agree.
