### ISSUE TITLE
Compiled files

### ISSUE THREAD

**Issue by glebmachine** [DavidOndrus/xliff-translator-tool#2]
Could you, please, share compiled files for Window/Mac/Linux?

**Comment by DavidOndrus** [comment]
They are available for download (Windows) in "[Releases](https://github.com/DavidOndrus/xliff-translator-tool/releases)" section of project.

**Comment by glebmachine** [comment]
Ooups, i'm missing that, thank you!
I think you might to add link to them right into README.md file
