### ISSUE TITLE
Crashes with German lang

### ISSUE THREAD

**Issue by zggb** [DavidOndrus/xliff-translator-tool#3]
Thank you for the useful app.
But when I try to open "de" file app is crashing

`      <trans-unit id="newsTableLabelLatest" datatype="html">
        <source>
        Latest news
      </source>
        <target>
        Empfehlungen
      </target>
        <context-group purpose="location">
          <context context-type="sourcefile">app/news/news.component.ts</context>
          <context context-type="linenumber">29</context>
        </context-group>
        <note priority="1" from="description">table label latest</note>
        <note priority="1" from="meaning">news-page</note>
      </trans-unit>`

**Comment by DavidOndrus** [comment]
I will take a look at it, thanks for your report

**Comment by zggb** [comment]
![out](https://user-images.githubusercontent.com/8955744/35385856-75bbbf38-01d2-11e8-8694-c8842b79773f.gif)

**Comment by DavidOndrus** [comment]
Thanks, please, can you send me the "messages.de.xlf" file or just it's content ? I don't need all trans-units, one should be enough but I need to see file header (all XLIFF tags).

**Comment by zggb** [comment]
[messages.de.xlf.zip](https://github.com/DavidOndrus/xliff-translator-tool/files/1663769/messages.de.xlf.zip)

**Comment by DavidOndrus** [comment]
Problem is in '&' char = this file is not valid XML format file.
For now, it can be fixed with encoding. '&' char should be '&amp;'. You can replace this occurence and everything should be fine.
But it does not mean that it should not be handled in my code so I will release new build soon.

**Comment by zggb** [comment]
Thank you for investigating these things.

**Comment by DavidOndrus** [comment]
Issue should be fixed now. Version 1.2 is up.
