### ISSUE TITLE
Merging in a file with added descriptions does not show the descriptions

### ISSUE THREAD

**Issue by schraal** [DavidOndrus/xliff-translator-tool#4]
I'm opening an existing translation and then import/merge a newly generated translation file in which descriptions are added to the i18n tags. The descriptions do not show in the tool

**Comment by DavidOndrus** [comment]
This was a feature, not a bug, as it is stated in the README, old translations are not touched by import.
But I decided to remake it so you can choose from 2 import modes.
Implemented in the latest version 1.3

**Comment by schraal** [comment]
thanks!
