### ISSUE TITLE
Support for Undo/Redo

### ISSUE THREAD

**Issue by dannyfhalpotia** [DavidOndrus/xliff-translator-tool#6]
Currently, if you accidentally type something in say the Identifier column, it is not possible to undo it. Redo does not work either. Not exactly bugs, but features that would be nice to have!

I don't mind forking and contributing with this feature?

**Comment by DavidOndrus** [comment]
Sorry for late reply, currently I'm out of time but I will try to implement undo/redo feature as soon as I have some free time.
Of course you can fork if you want.

**Comment by DavidOndrus** [comment]
I've made a small research about this feature in WPF DataGrid and I've found out that Undo/Redo works while you are in the cell. History is deleted as soon as you leave that cell. There are a few options of implementation but they are not 15-minute things and I can't invest my time into it now.
Closing the issue for now, feel free to contribute if you want this feature.
