### ISSUE TITLE
Nested expressions are lost

### ISSUE THREAD

**Issue by BSchuhmacher** [DavidOndrus/xliff-translator-tool#7]
Hi

If you have an i18n string containing some HTML codes ng xi18n extracts theme in an "own" format.
As it seems they are all discarded when the file is opend with XLIFF Translator Tool.

For example if you HTML Template shows
`<p i18n>Here is something to <span (click)="doSomething">click</span> and a <a href="link/to/something">link</a>`

it is extracted to
`Here is something to<x id="START_TAG_SPAN" ctype="x-span" equiv-text="&lt;span&gt;"/>click<x id="CLOSE_TAG_SPAN" ctype="x-span" equiv-text="&lt;/span&gt;"/> and a <x id="START_LINK" ctype="x-a" equiv-text="&lt;a&gt;"/>link<x id="CLOSE_LINK" ctype="x-a" equiv-text="&lt;/a&gt;"/>`

As it seems all the parts in "<...>" are dropped when reading the xlf file.

I think this is not good, as the format is like nested expressions mentioned in the angular documentation.

**Comment by DavidOndrus** [comment]
Thanks for report,
the issue should be fixed in the latest version (1.4).
