### ISSUE TITLE
Encoding value changed in resulting xlf file

### ISSUE THREAD

**Issue by TitaneBoy** [DavidOndrus/xliff-translator-tool#8]
Hi @DavidOndrus . I was testing your application and I was wondering why the enconding is changed in the resulting xlf file as you can see here ?

![image](https://user-images.githubusercontent.com/15614466/43922073-a596e896-9beb-11e8-921d-6add19b65b78.png)

In my example, should it not keep the "UTF-8" enconding in the final xlf ?

Thanks in advance for your answer.

**Comment by DavidOndrus** [comment]
Hi, sorry for my very late answer.
That's a strange issue since I create XML file in code with this line:
XmlNode docNode = xmlDocument.CreateXmlDeclaration("1.0", "UTF-8", null);
I would rather say that the first one is the file output from my utility because the second one doesn't make sense.

**Comment by TitaneBoy** [comment]
@DavidOndrus ... I will try to re-investigate this case.. I'm pretty sure that I didn't change anything but I will do other batch of tests... Thanks for your answer

**Comment by Andrey-Pavlov** [comment]
Have the same issue here: It changes encoding from UTF-8 to UTF-16

**Comment by DavidOndrus** [comment]
possible fix in fork https://github.com/JaronPiet/xliff-translator-tool
