### ISSUE TITLE
Getting this running on Linux through Wine

### ISSUE THREAD

**Issue by Bullace** [DavidOndrus/xliff-translator-tool#9]
So I'm trying to get this to run on Linux through Wine without much success so far. Could you tell me if this application is 32 or 64 bit and what version of .NET this requires so I can do some more fiddling.

**Comment by DavidOndrus** [comment]
Target framework is .NET 4.6.1
Platform target is "Any CPU" so it should support both x86 and x64 but 32-bit is preferred.
